### ISSUE TITLE
django-proxy is not python3

### ISSUE THREAD

**Issue by deronnax** [mjumbewu/django-proxy#3]
django-proxy is not python3 whereas setup.py qualifiers tell it is.
Interested by me porting to python 3 ?

**Comment by mjumbewu** [comment]
Yeah, that would be great. If you can, add a test that demonstrates current failure in Python 3 as well (I know there aren't tests yet and I'm ashamed :disappointed:).

**Comment by deronnax** [comment]
What the python 3 test would fail on ?

**Comment by amarandon** [comment]
If I may  add my humble opinion to the discussion, one doesn't typically test for a specific version of Python. The typical approach is to write tests that test actual features and run them against a different versions of Python, possibly with the help of tools like Travis or Tox. More likely than not this will highlight compatibility problems with some versions.

**Comment by mjumbewu** [comment]
Yes, that's absolutely what I mean. If django-proxy is not working with
python3, there should be some test that would pass on python2 and not on
python3. I haven't poked around with this myself yet, but hopefully I will
get the time this weekend.
